@hostname = localhost
@port = 8080
@base_url = http://{{hostname}}:{{port}}
@customer_path = /api/v1/customer
@manager_path = /api/v1/manager
@system_path = /api/v1/system
@token = eyJhbGciOiJIUzI1NiJ9.eyJkbmkiOiIyMjIyMjIyMkoiLCJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTM1ODEwOCwiZXhwIjoxNzY5MzU4Mjg4fQ.KXHngdSRm45n-tuXxDHYzyQ1_2wMrqiQuqpGtVLv7xg
@refreshToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzY5MzU3NDYyLCJleHAiOjE3Njk5NjIyNjJ9.PaW0K3yWVuJsoxx53hOrp5y49Re-zN0GrWKXH57jVsM

### MethodArgumentTypeMismatchException
GET {{base_url}}{{manager_path}}/a
Authorization: Bearer {{token}}

### IllegalArgumentException
PATCH {{base_url}}{{manager_path}}/f47ac10b-58cc-4372-a567-0e02b2c3d479
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "CANCELLED"
}

### LoanApplicationNotFoundException
GET {{base_url}}{{manager_path}}/f47ac10b-58cc-4372-a567-0e02b2c3d471
Authorization: Bearer {{token}}

### HttpMessageNotReadableException
# Mensaje invalido por formato
POST {{base_url}}{{customer_path}}/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "applicantName": "John Doe",
    "requestedAmount": 1000f,
    "currency": "EUR",
    "applicantDni": "12345678Z"
}

### MethodArgumentNotValidException
# No cumple las validaciones del @Valid dto 
POST {{base_url}}{{customer_path}}/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "applicantName": "John Doe",
    "requestedAmount": 1000,
    "currency": "EUR",
    "applicantDni": "12345678A",
    "status": "PENDING"
}

### HttpRequestMethodNotSupportedException
DELETE {{base_url}}{{customer_path}}/
Authorization: Bearer {{token}}