spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
      # apaga los contenedores al detener la app
      lifecycle-management: start_and_stop
      # los contenedores estarán listos antes que el contexto de Spring
      startup:
        wait: always
      readiness:
        timeout: 5m
      # profiles:
      #   active: dev
  datasource:
    url: jdbc:mysql://localhost:3307/caixabank
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
  flyway:
    enabled: true
    schemas: caixabank
    locations:
      - classpath:db/flyway/mysql
    # Al no poner URL aquí, Flyway usa el mismo DataSource que la app principal
    baseline-on-migrate: true
    default-schema: caixabank

logging:
  file:
    # Nombre y ruta del archivo de log donde se escribirán los mensajes.
    # Este archivo se creará en el directorio de ejecución de la aplicación.
    name: logs/app.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name:-},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %5p [${spring.application.name:-},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

management:
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4317
  endpoints:
    web:
      exposure:
        include: "*" # Necesario para que Actuator exponga los datos
