spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    # URL simplificada para evitar errores de metadatos/dialecto
    url: jdbc:h2:mem:caixabank;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.default_schema: caixabank
  flyway:
    enabled: true
    schemas: caixabank
    locations:
      - classpath:db/flyway/h2
    # Al no poner URL aquí, Flyway usa el mismo DataSource que la app principal
    baseline-on-migrate: true
    default-schema: caixabank

auth:
  access-token-secret-key: lMCvj7Sirkk41OpuXDBKoSA1YeQ4aTeHmP4gzoyoaLk=
  access-token-expiration: 180000
  refresh-token-secret-key: laCvj7Sirkk41OpuXDBKoSA1YeQ4aTeHmP4gzoyoaLk=
  refresh-token-expiration: 604800000
